spring:
  profiles:
    include: SECRET-KEY

  datasource:
    url: jdbc:mysql://${database-host}/etadb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${database-password}

  jpa:
    database: mysql
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    generate-ddl: true

server:
  port: 8085