spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}/etadb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${DATABASE_PASSWORD}

  redis:
    port: 6379
    host: localhost

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
            redirect-uri: ${REDIRECT_URI}

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    database: mysql
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    generate-ddl: true

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expire-length: 1800000
  refresh:
    token:
      expire-day: 1

---

server:
  port: 8085

cors:
  allowed:
    origins: http://localhost:8888
