spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}/etadb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${DATABASE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email

  jpa:
    database: mysql
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    generate-ddl: true

server:
  port: 8085